### ISSUE TITLE
provider/virtualbox/synced_folder test does not work

### ISSUE THREAD

**Issue by Gray-Wind** [mitchellh/vagrant-spec#13]
Looks like synced_folder test cannot be successful ever because local path `.` redirected to `/foo` and disabled in the skeleton.

I run the test with these commands in the vagrant project:

```bash
$ bundle install --path vendor/bundle
$ bundle exec vagrant-spec test --components=provider/virtualbox/synced_folder
```

I use this distributive:
https://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.5-x86_64-v20140504.box

And after all output is:

```
provider/virtualbox/synced_folder
  it should behave like provider/synced_folder
    properly configures synced folder types
      Execute: vagrant box add basic /Users/gw/projects/parallels/vagrant/boxes/CentOS-6.5-x86_64-v20140504.box
      Execute: vagrant up --provider=virtualbox
      Test: mounts the default /vagrant synced folder
      Execute: vagrant ssh -c cat /vagrant/foo
      Execute: vagrant destroy --force
      properly configures synced folder types (FAILED - 1)

Failures:

  1) provider/virtualbox/synced_folder it should behave like provider/synced_folder properly configures synced folder types
     Failure/Error: Unable to find matching line from backtrace

       expected: 0
            got: 1

       (compared using eql?)
     Shared Example Group: "provider/synced_folder" called from .-spec/lib/vagrant-spec/acceptance/runner.rb:64
     # .-spec/acceptance/provider/synced_folder_spec.rb:26:in `block (2 levels) in <top (required)>'
     # .-spec/lib/vagrant-spec/acceptance/runner.rb:43:in `block in run'
     # .-spec/lib/vagrant-spec/acceptance/runner.rb:76:in `with_world'
     # .-spec/lib/vagrant-spec/acceptance/runner.rb:28:in `run'
     # .-spec/lib/vagrant-spec/cli.rb:34:in `test'

Finished in 58.93 seconds
1 example, 1 failure

Failed examples:

rspec .-spec/acceptance/provider/synced_folder_spec.rb:23 # provider/virtualbox/synced_folder it should behave like provider/synced_folder properly configures synced folder types
```

**Comment by legal90** [comment]
It was fixed by #18
