### ISSUE TITLE
"acceptance" shared context goes missing when running acceptance components

### ISSUE THREAD

**Issue by BaxterStockman** [mitchellh/vagrant-spec#25]
I'm hitting an `ArgumentError` when running `vagrant spec test` because RSpec can't find the shared context "acceptance".  The issue can be exposed by running `vagrant-spec`'s own acceptance tests.  Given:

```ruby
# vagrant-spec.config.rb

Vagrant::Spec::Acceptance.configure do |config|
  config.component_paths << 'acceptance'
end
```

in the `vagrant-spec` repository root, running `vagrant-spec test` results in the following trace:

```
auser@somehost $ bundle exec vagrant-spec test
bundler: failed to load command: vagrant-spec (/home/auser/.gem/ruby/2.3.3/bin/vagrant-spec)
ArgumentError: Could not find shared context "acceptance"
  /home/auser/.gem/ruby/2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:370:in `find_and_eval_shared'
  /home/auser/.gem/ruby/2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:331:in `include_context'
  /home/auser/git/vagrant-spec/acceptance/cli/box_spec.rb:2:in `block in <top (required)>'
  /home/auser/.gem/ruby/2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:385:in `module_exec'
  /home/auser/.gem/ruby/2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:385:in `subclass'
  /home/auser/.gem/ruby/2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:258:in `block in define_example_group_method'
  /home/auser/.gem/ruby/2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/dsl.rb:43:in `block in expose_example_group_alias'
  /home/auser/.gem/ruby/2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/dsl.rb:84:in `block (2 levels) in expose_example_group_alias_globally'
  /home/auser/git/vagrant-spec/acceptance/cli/box_spec.rb:1:in `<top (required)>'
  /home/auser/git/vagrant-spec/lib/vagrant-spec/components.rb:22:in `load'
  /home/auser/git/vagrant-spec/lib/vagrant-spec/components.rb:22:in `block (3 levels) in reload!'
  /home/auser/git/vagrant-spec/lib/vagrant-spec/components.rb:21:in `each'
  /home/auser/git/vagrant-spec/lib/vagrant-spec/components.rb:21:in `block (2 levels) in reload!'
  /home/auser/git/vagrant-spec/lib/vagrant-spec/components.rb:20:in `each'
  /home/auser/git/vagrant-spec/lib/vagrant-spec/components.rb:20:in `block in reload!'
  /home/auser/git/vagrant-spec/lib/vagrant-spec/components.rb:60:in `with_world'
  /home/auser/git/vagrant-spec/lib/vagrant-spec/components.rb:16:in `reload!'
  /home/auser/git/vagrant-spec/lib/vagrant-spec/components.rb:11:in `initialize'
  /home/auser/git/vagrant-spec/lib/vagrant-spec/acceptance/runner.rb:12:in `new'
  /home/auser/git/vagrant-spec/lib/vagrant-spec/acceptance/runner.rb:12:in `initialize'
  /home/auser/git/vagrant-spec/lib/vagrant-spec/cli.rb:31:in `new'
  /home/auser/git/vagrant-spec/lib/vagrant-spec/cli.rb:31:in `test'
  /home/auser/.gem/ruby/2.3.3/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
  /home/auser/.gem/ruby/2.3.3/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
  /home/auser/.gem/ruby/2.3.3/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
  /home/auser/.gem/ruby/2.3.3/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
  /home/auser/git/vagrant-spec/bin/vagrant-spec:7:in `<top (required)>'
  /home/auser/.gem/ruby/2.3.3/bin/vagrant-spec:22:in `load'
  /home/auser/.gem/ruby/2.3.3/bin/vagrant-spec:22:in `<top (required)>'
```

The cause of the issue appears to be the fact that the "acceptance" shared context is added to the core `RSpec.world.shared_example_group_registry` rather than the registry on the world object in scope during `Vagrant::Spec::Acceptance::Runner#with_world` and `Vagrant::Spec::Components#with_world`:

```ruby
# vagrant-spec/components.rb 
      # Loads the components from the given paths
      def reload!
        binding.pry # drop to REPL
        with_world do
          binding.pry # ...and again
          # Delete the existing example groups
          @world.example_groups.clear

          @paths.each do |path|
            Dir.glob(File.join(path, "**/*_{output,spec}.rb")).each do |single|
              load single
            end
          end
        end
      end
```

```
auser@somehost $ bundle exec ruby -rpry ./bin/vagrant-spec test

From: /home/auser/git/vagrant-spec/lib/vagrant-spec/components.rb @ line 16 Vagrant::Spec::Components#reload!:

    15: def reload!
 => 16:   binding.pry # Drop to REPL
    17:   with_world do
    18:     binding.pry # ...and again
    19:     # Delete the existing example groups
    20:     @world.example_groups.clear
    21:
    22:     @paths.each do |path|
    23:       Dir.glob(File.join(path, "**/*_{output,spec}.rb")).each do |single|
    24:         load single
    25:       end
    26:     end
    27:   end
    28: end

[1] pry(#<Vagrant::Spec::Components>)> RSpec.world.shared_example_group_registry.send(:shared_example_groups)
=> {:main=>{"acceptance"=>#<RSpec::Core::SharedExampleGroupModule "acceptance">}}
[2] pry(#<Vagrant::Spec::Components>)>

From: /home/auser/git/vagrant-spec/lib/vagrant-spec/components.rb @ line 18 Vagrant::Spec::Components#reload!:

    15: def reload!
    16:   binding.pry # drop to REPL
    17:   with_world do
 => 18:     binding.pry # ...and again
    19:     # Delete the existing example groups
    20:     @world.example_groups.clear
    21:
    22:     @paths.each do |path|
    23:       Dir.glob(File.join(path, "**/*_{output,spec}.rb")).each do |single|
    24:         load single
    25:       end
    26:     end
    27:   end
    28: end

[1] pry(#<Vagrant::Spec::Components>)> RSpec.world.shared_example_group_registry.send(:shared_example_groups)
=> {}
[2] pry(#<Vagrant::Spec::Components>)>
```
This can be solved by evaluating `vagrant-spec/acceptance/rspec/context.rb` within a `with_world` block.  Not quite sure how best to go about achieving this, but I'd be happy to put a PR together.

**Comment by BaxterStockman** [comment]
Closing as this appears to be solved by 76f9c43efc4ca7b524df1fae81817c6ef16a2d97.  Thanks, @chrisroberts!
